sonar.organization=obldevops
sonar.projectKey=OblDevOps_ReatilStore
sonar.projectName=ReatilStore
sonar.sources=.
sonar.exclusions=**/*_test.go,**/vendor/**
sonar.go.coverage.reportPaths=coverage.out
